server:
  port: 3033
  kill-9:
    pid: 1234
    master-pass: 3920192
db:
  motor: postgresql
  host: localhost
  database: beplus_example_db
  schema: ext
  user: beplus_example_user
  password: beplus_example_3948812bdz
login:
  table: users
  userFieldName: username
  passFieldName: md5pass
  infoFieldList: [username, rol]
  plus:
    fileStore: true
    loginForm:
      formTitle: example tables
      formImg: unlogged/tables-lock.png
