language: node_js
node_js:
  - "8"
  - "9"
matrix:
  fast_finish: true
script: "npm run-script test-ci"
after_script: "npm install coveralls@2.11.9 && cat ./coverage/lcov.info | coveralls"
dist: trusty
sudo: required
addons:
  postgresql: "9.5"
before_script:
  - psql -c 'create user test_user password $$test_pass$$;' -U postgres
  - psql -c 'create database test_db owner test_user;' -U postgres
  - psql -U postgres -f test/populate_db.sql test_db
