language: node_js
node_js:
  - "4"
  - "6"
  - "7"
matrix:
  fast_finish: true
  allow_failures:
    - node_js: "7"
script: "npm run-script test-ci"
after_script: "npm install coveralls@2.11.9 && cat ./coverage/lcov.info | coveralls"
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create user test_user password $$test_pass$$;' -U postgres
  - psql -c 'create database test_db owner test_user;' -U postgres
  - psql -U postgres -f test/populate_db.sql test_db
