server:
  port: 3030
  release: 20160613b
db:
  motor: postgresql
  host: localhost
  database: beplus_example_db
  schema: bep
  user: beplus_example_user
  password: beplus_example_3948812bdz
login:
  table: users
  userFieldName: username
  passFieldName: md5pass
  infoFieldList: [username, rol, iddato]
  plus:
    fileStore: true
    loginForm:
      usernameLabel: abonado
      passwordLabel: clave
      formTitle: registro
      buttonLabel: entrar
      autoLogin: true
estructura:
  origen: ejemplos/estructura-ejemplo.yaml