server:
  port: 3033
  kill-9:
    pid: 1234
    master-pass: 3920192
  skins:
    "":
      local-path: client/
    confort:
      local-path: node_modules/backend-skins/dist/
    confort-bis:
      local-path: node_modules/backend-skins/dist/confort-bis
db:
  motor: postgresql
  host: localhost
  database: beplus_example_db
  schema: ext
  user: beplus_example_user
  password: beplus_example_3948812bdz
login:
  table: users
  userFieldName: username
  passFieldName: md5pass
  rolFieldName: rol
  infoFieldList: [username, rol]
  activeClausule: current_timestamp<=active_until
  lockedClausule: current_timestamp>=locked_since
  plus:
    allowHttpLogin: true
    chPassUrlPath: false
    fileStore: true
    secret: secret cat in the table
    loginForm:
      formTitle: example tables
      formImg: unlogged/tables-lock.png
    x-loginPagePath: false
client-setup:
  cursors: true
  skin: confort-bis
  formTitle: example-tables
logo: 
  path: client/img