db:
  port: 5435
  password: beplus_example_3948812bdz
log:
  req: true
login:
  plus:
    secret: false
    allowHttpLogin: true
devel:
  forceShowAsEditable: true    
client-setup:
  skin: "confort"
  lang: es
server:  
  skins:
    confort:
      local-path: ../backend-skins/dist/
  kill-9:
    master-pass: 3920192
devel:
  useFileDevelopment: true
  delay: 400
  cache-content: true
  forceShowAsEditable: false