db:
  port: 5435
log:
  req: true
login:
  plus:
    secret: false
    allowHttpLogin: true
devel:
  forceShowAsEditable: true    
client-setup:
  skin: "confort"
  lang: es
server:  
  skins:
    confort:
      local-path: ../backend-skins/dist/
